hostNetwork: true

controller:
  nginxDebug: true

service:
  type: "LoadBalancer"
  targetPorts:
    https: 80
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

extraArgs:
  default-ssl-certificate: "default/main-tls"
